### ISSUE TITLE
Audit Logs

### ISSUE THREAD

**Issue by kharton03** [jaroslavhuss/uuiot#48]
Hi All,

anyone can help for may project?

where do i find these ff Audit logs?

Audit Logs - Access to audit trails
Audit Logs - Privilege Elevation
Audit Logs - Initialization of Audit Logging
Audit Logs - Stop or Pause of Audit Logging
Audit Logs - Root Action
Audit Logs - Add, Delete, Change to Accounts
Audit Logs - Creation Deletion of System Objects

Thanks in advance :)

**Comment by jaroslavhuss** [comment]
I am sorry, this is a personal/school project under the construction. We can not help you at this moment.
